package io.github.sensitivescanner.model;
public enum Location {
    REQUEST_URL, REQUEST_QUERY, REQUEST_HEADER, REQUEST_COOKIE, REQUEST_BODY,
    RESPONSE_HEADER, RESPONSE_COOKIE, RESPONSE_BODY, RESPONSE_JAVASCRIPT
}
